In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.metrics import mean_squared_error , mean_absolute_error
from sklearn.linear_model import ElasticNet
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor

In [3]:
aapl = pd.read_csv("stocks/AAPL.csv")
qqq = pd.read_csv("etfs/QQQ.csv")
msft = pd.read_csv("stocks/MSFT.csv")
nvda = pd.read_csv("stocks/NVDA.csv")
amzn = pd.read_csv("stocks/AMZN.csv")
orcl = pd.read_csv("stocks/ORCL.csv")
googl = pd.read_csv("stocks/GOOGL.csv")

In [4]:
aapl["Date"]= pd.to_datetime(aapl["Date"])
aapl.set_index("Date", inplace=True)
print(aapl.shape)
print(aapl.head(5))

(9909, 6)
                Open      High       Low     Close  Adj Close     Volume
Date
1980-12-12  0.513393  0.515625  0.513393  0.513393   0.406782  117258400
1980-12-15  0.488839  0.488839  0.486607  0.486607   0.385558   43971200
1980-12-16  0.453125  0.453125  0.450893  0.450893   0.357260   26432000
1980-12-17  0.462054  0.464286  0.462054  0.462054   0.366103   21610400
1980-12-18  0.475446  0.477679  0.475446  0.475446   0.376715   18362400

In [5]:
qqq["Date"]= pd.to_datetime(qqq["Date"])
qqq.set_index("Date", inplace=True)
print(qqq.shape)
print(qqq.head(5))

(5301, 6)
                Open       High       Low    Close  Adj Close   Volume
Date
1999-03-10  51.12500  51.156250  50.28125  51.0625  44.600906  5232000
1999-03-11  51.43750  51.734375  50.31250  51.3125  44.819260  9688600
1999-03-12  51.12500  51.156250  49.65625  50.0625  43.727436  8743600
1999-03-15  50.43750  51.562500  49.90625  51.5000  44.983032  6369000
1999-03-16  51.71875  52.156250  51.15625  51.9375  45.365170  4905800

In [6]:
msft["Date"]= pd.to_datetime(msft["Date"])
msft.set_index("Date", inplace=True)
print(msft.shape)
print(msft.head(5))

(8584, 6)
                Open      High       Low     Close  Adj Close      Volume
Date
1986-03-13  0.088542  0.101562  0.088542  0.097222   0.062378  1031788800
1986-03-14  0.097222  0.102431  0.097222  0.100694   0.064606   308160000
1986-03-17  0.100694  0.103299  0.100694  0.102431   0.065720   133171200
1986-03-18  0.102431  0.103299  0.098958  0.099826   0.064049    67766400
1986-03-19  0.099826  0.100694  0.097222  0.098090   0.062935    47894400

In [7]:
nvda["Date"]= pd.to_datetime(nvda["Date"])
nvda.set_index("Date", inplace=True)
print(nvda.shape)
print(nvda.head(5))

(5334, 6)
                Open      High       Low     Close  Adj Close      Volume
Date
1999-01-22  1.750000  1.953125  1.552083  1.640625   1.509998  67867200.0
1999-01-25  1.770833  1.833333  1.640625  1.812500   1.668188  12762000.0
1999-01-26  1.833333  1.869792  1.645833  1.671875   1.538759   8580000.0
1999-01-27  1.677083  1.718750  1.583333  1.666667   1.533965   6109200.0
1999-01-28  1.666667  1.677083  1.651042  1.661458   1.529172   5688000.0

In [8]:
amzn["Date"]= pd.to_datetime(amzn["Date"])
amzn.set_index("Date", inplace=True)
print(amzn.shape)
print(amzn.head(5))

(5758, 6)
                Open      High       Low     Close  Adj Close    Volume
Date
1997-05-15  2.437500  2.500000  1.927083  1.958333   1.958333  72156000
1997-05-16  1.968750  1.979167  1.708333  1.729167   1.729167  14700000
1997-05-19  1.760417  1.770833  1.625000  1.708333   1.708333   6106800
1997-05-20  1.729167  1.750000  1.635417  1.635417   1.635417   5467200
1997-05-21  1.635417  1.645833  1.375000  1.427083   1.427083  18853200

In [9]:
orcl["Date"]= pd.to_datetime(orcl["Date"])
orcl.set_index("Date", inplace=True)
print(orcl.shape)
print(orcl.head(5))

(8585, 6)
                Open      High       Low     Close  Adj Close     Volume
Date
1986-03-12  0.063272  0.064043  0.063272  0.063272   0.055091  393012000
1986-03-13  0.064815  0.065586  0.064815  0.064815   0.056434  125290800
1986-03-14  0.067130  0.067901  0.067130  0.067130   0.058450   57866400
1986-03-17  0.066358  0.066358  0.065586  0.065586   0.057106   28285200
1986-03-18  0.064815  0.064815  0.064043  0.064043   0.055762   32335200

In [10]:
googl["Date"]= pd.to_datetime(googl["Date"])
googl.set_index("Date", inplace=True)
print(googl.shape)
print(googl.head(5))

(3932, 6)
                 Open       High        Low      Close  Adj Close    Volume
Date
2004-08-19  50.050049  52.082081  48.028027  50.220219  50.220219  44659000
2004-08-20  50.555557  54.594593  50.300301  54.209209  54.209209  22834300
2004-08-23  55.430431  56.796795  54.579578  54.754753  54.754753  18256100
2004-08-24  55.675674  55.855854  51.836838  52.487488  52.487488  15247300
2004-08-25  52.532532  54.054054  51.991993  53.053055  53.053055   9188600

In [11]:
companies={"aapl": aapl,
           "qqq" : qqq,
           "msft": msft,
           "nvda": nvda,
           "amzn": amzn,
           "orcl": orcl,
          "googl": googl}

In [12]:
for name, df in companies.items():
    companies[name] = df[df.index >= "2018-01-01"]

In [13]:
for name, df in companies.items():
    companies[name] = df["Adj Close"]

In [14]:
print(companies["aapl"].shape)
print(companies["qqq"].shape)
print(companies["msft"].shape)
print(companies["nvda"].shape)
print(companies["amzn"].shape)
print(companies["orcl"].shape)
print(companies["googl"].shape)

(566,)
(566,)
(566,)
(566,)
(566,)
(566,)
(566,)

In [15]:
companies["aapl"]

Date
2018-01-02    166.804016
2018-01-03    166.774963
2018-01-04    167.549622
2018-01-05    169.457214
2018-01-08    168.827820
                 ...
2020-03-26    258.440002
2020-03-27    247.740005
2020-03-30    254.809998
2020-03-31    254.289993
2020-04-01    240.910004
Name: Adj Close, Length: 566, dtype: float64

In [16]:
returns ={}
for name,df in companies.items():
    returns[name]= df.pct_change()

In [17]:
returns["aapl"].head()

Date
2018-01-02         NaN
2018-01-03   -0.000174
2018-01-04    0.004645
2018-01-05    0.011385
2018-01-08   -0.003714
Name: Adj Close, dtype: float64

In [18]:
d_returns=pd.DataFrame(returns)
print(d_returns.head())
print(d_returns.shape)

                aapl       qqq      msft      nvda      amzn      orcl  \
Date
2018-01-02       NaN       NaN       NaN       NaN       NaN       NaN
2018-01-03 -0.000174  0.009717  0.004654  0.065814  0.012775  0.023161
2018-01-04  0.004645  0.001750  0.008802  0.005271  0.004476  0.009851
2018-01-05  0.011385  0.010043  0.012398  0.008474  0.016163  0.006019
2018-01-08 -0.003714  0.003891  0.001020  0.030641  0.014425  0.010522

               googl
Date
2018-01-02       NaN
2018-01-03  0.017061
2018-01-04  0.003884
2018-01-05  0.013260
2018-01-08  0.003531
(566, 7)

In [19]:
d_returns.dropna(inplace=True)

In [20]:
d_returns.isnull().sum()

aapl     0
qqq      0
msft     0
nvda     0
amzn     0
orcl     0
googl    0
dtype: int64

In [21]:
d_returns.shape

(565, 7)

In [22]:
d_returns["target"] = d_returns["aapl"].shift(-1)
d_returns.shape

(565, 8)

In [23]:
d_returns.dropna(inplace=True)

In [24]:
d_returns.shape

(564, 8)

In [25]:
train= d_returns[(d_returns.index >= "2018-01-01") & (d_returns.index <"2019-01-01")]
val  = d_returns[(d_returns.index >= "2019-01-01") & (d_returns.index <"2020-01-01")]
test = d_returns[(d_returns.index >= "2020-01-01") & (d_returns.index <"2021-01-01")]

In [26]:
print(train.shape)
print(val.shape)
print(test.shape)

(250, 8)
(252, 8)
(62, 8)

In [27]:
d_returns

,aapl,qqq,msft,nvda,amzn,orcl,googl,target
Date,,,,,,,,
2018-01-03,-0.000174,0.009717,0.004654,0.065814,0.012775,0.023161,0.017061,0.004645
2018-01-04,0.004645,0.001750,0.008802,0.005271,0.004476,0.009851,0.003884,0.011385
2018-01-05,0.011385,0.010043,0.012398,0.008474,0.016163,0.006019,0.013260,-0.003714
2018-01-08,-0.003714,0.003891,0.001020,0.030641,0.014425,0.010522,0.003531,-0.000115
2018-01-09,-0.000115,0.000062,-0.000680,-0.000270,0.004676,0.005534,-0.001274,-0.000230
...,...,...,...,...,...,...,...,...
2020-03-25,-0.005509,-0.007405,-0.009573,-0.014287,-0.027968,-0.039716,-0.025124,0.052623
2020-03-26,0.052623,0.052660,0.062551,0.047309,0.036933,0.098825,0.055645,-0.041402
2020-03-27,-0.041402,-0.034393,-0.041061,-0.017532,-0.028325,-0.012876,-0.045283,0.028538
2020-03-30,0.028538,0.036373,0.070341,0.050884,0.033603,0.010636,0.032470,-0.002041
2020-03-31,-0.002041,-0.008540,-0.015727,-0.007493,-0.007246,-0.040310,0.013644,-0.052617

In [28]:
x_train= train.iloc[:,:-1]
y_train=train.iloc[:,-1]

x_val= val.iloc[:,:-1]
y_val=val.iloc[:,-1]

x_test= test.iloc[:,:-1]
y_test= test.iloc[:,-1]

In [29]:
print(x_train.shape)
print(y_train.shape)
print(x_val.shape)
print(y_val.shape)
print(x_test.shape)
print(y_test.shape)

(250, 7)
(250,)
(252, 7)
(252,)
(62, 7)
(62,)

In [30]:
model1= ElasticNet(alpha=0.1, l1_ratio=0.5)
model1.fit(x_train,y_train)
pred_en=model1.predict(x_val)
mae= mean_absolute_error(y_val, pred_en)
rmse =mean_squared_error(y_val, pred_en)**0.5

In [31]:
print(mae)
print(rmse)

0.011751730573643928
0.016730152540561705

In [32]:
model2= RandomForestRegressor(n_estimators=100)
model2.fit(x_train,y_train)
pred_en2= model2.predict(x_val)
mae2= mean_absolute_error(y_val, pred_en2)
rmse2= mean_squared_error(y_val,pred_en2)**0.5

In [33]:
print(mae2)
print(rmse2)

0.012283075844483704
0.017087976251643624

In [34]:
model3=GradientBoostingRegressor()
model3.fit(x_train,y_train)
pred_en3=model3.predict(x_val)
mae3= mean_absolute_error(y_val, pred_en3)
rmse3= mean_squared_error(y_val, pred_en3)**0.5

In [35]:
print(mae3)
print(rmse3)

0.012556302559802418
0.017150877524531576

In [36]:
pred_ensemble=np.mean([pred_en, pred_en2 , pred_en3], axis=0)
mae4= mean_absolute_error(y_val,pred_ensemble)
rmse4= mean_squared_error(y_val, pred_ensemble)**0.5

In [37]:
print(mae4)
print(rmse4)

0.011785985578424073
0.016629462668239708

In [38]:
x_train_val= pd.concat([x_train, x_val])
y_train_val= pd.concat([y_train , y_val])

model1.fit(x_train_val,y_train_val)
predict1= model1.predict(x_test)
tmae1= mean_absolute_error(y_test,predict1)
trmse1= mean_squared_error(y_test, predict1)**0.5

model2.fit(x_train_val,y_train_val)
predict2= model2.predict(x_test)
tmae2= mean_absolute_error(y_test,predict2)
trmse2= mean_squared_error(y_test, predict2)**0.5

model3.fit(x_train_val,y_train_val)
predict3= model3.predict(x_test)
tmae3= mean_absolute_error(y_test,predict3)
trmse3= mean_squared_error(y_test, predict3)**0.5

ensemble= np.mean([predict1, predict2, predict3], axis=0)
tmae4= mean_absolute_error(y_test,ensemble)
trmse4= mean_squared_error(y_test, ensemble)**0.5

In [39]:
print(tmae1)
print(trmse1)

print(tmae2)
print(trmse2)

print(tmae3)
print(trmse3)

print(tmae4)
print(trmse4)

0.02925452626570984
0.04200295360251691
0.029541531188260566
0.043318079994800564
0.029174927412515372
0.04288172779458171
0.029046809404961623
0.04233042493275537

In [40]:
def accuracy(actual_l, pred_l):
    return (np.sign(actual_l)==np.sign(pred_l)).mean()

actual_label= np.sign(y_test)

pred_label1= np.sign(predict1)
model1_accuracy= accuracy(actual_label,pred_label1)

pred_label2= np.sign(predict2)
model2_accuracy= accuracy(actual_label,pred_label2)

pred_label3= np.sign(predict3)
model3_accuracy= accuracy(actual_label,pred_label3)

pred_label4= np.sign(ensemble)
model4_accuracy= accuracy(actual_label,pred_label4)

In [41]:
print(model1_accuracy)
print(model2_accuracy)
print(model3_accuracy)
print(model4_accuracy)

0.43548387096774194
0.5483870967741935
0.5
0.532258064516129

In [45]:
def pre_hat(value):
    return [value * (1+ i) for i in ensemble]

date_df= x_test.index.to_frame(index=False)
date_df.set_index("Date", inplace=True)
date_df["Ticker"]= ["AAPL" for _ in range (len(date_df)) ]
date_df["r_hat_next"]= ensemble
date_df["p_hat_next"] = companies["aapl"][x_test.index].values * (1 + ensemble)

In [58]:
date_df.head()

           Ticker  r_hat_next  p_hat_next
Date
2020-01-02   AAPL    0.004934  301.117284
2020-01-03   AAPL    0.003603  297.794897
2020-01-06   AAPL    0.004394  300.404274
2020-01-07   AAPL    0.004682  299.077201
2020-01-08   AAPL    0.005386  304.101377

In [60]:
date_df.to_csv("Prediction.csv")

In [66]:
x_train.head()

,aapl,qqq,msft,nvda,amzn,orcl,googl
Date,,,,,,,
2018-01-03,-0.000174,0.009717,0.004654,0.065814,0.012775,0.023161,0.017061
2018-01-04,0.004645,0.001750,0.008802,0.005271,0.004476,0.009851,0.003884
2018-01-05,0.011385,0.010043,0.012398,0.008474,0.016163,0.006019,0.013260
2018-01-08,-0.003714,0.003891,0.001020,0.030641,0.014425,0.010522,0.003531
2018-01-09,-0.000115,0.000062,-0.000680,-0.000270,0.004676,0.005534,-0.001274

In [ ]:
model1

In [72]:
metrics_table= pd.DataFrame({
    "Models"                 : ["Elastic Net", "Random Forest", "Gradient Boosting", "Average of all model"],
    "Mean Absolute Error"    : [tmae1, tmae2, tmae3, tmae4],
    "Root Mean Squared Error": [trmse1, trmse2, trmse3, trmse4],
    "Accuracy"               : [model1_accuracy, model2_accuracy, model3_accuracy, model4_accuracy]
})

In [74]:
metrics_table

,Models,Mean Absolute Error,Root Mean Squared Error,Accuracy
0,Elastic Net,0.029255,0.042003,0.435484
1,Random Forest,0.029542,0.043318,0.548387
2,Gradient Boosting,0.029175,0.042882,0.500000
3,Average of all model,0.029047,0.042330,0.532258

In [75]:
metrics_table.to_csv("metrics.csv")